export default {
	gz_daqiush0: "汉大秋实零",
	gz_daqiush1: "魏大秋蜀一",
	gz_daqiush2: "从魏大秋蜀二",
	gz_daqiush3: "汉大秋实三",
	gz_daqiush4: "汉大秋实四",
	gz_daqiush5: "汉大秋实五",
	gz_daqiush6: "汉大秋实六",
	gz_daqiush7: "汉大秋实七",
	gz_daqiush8: "汉大秋实八",
	gz_daqiush9: "汉大秋实九",
	gz_daqiush10: "汉大秋实十",
	gz_daqiush11: "大秋蜀十一",
	gz_daqiush12: "大秋蜀十二",
	gz_daqiush13: "大秋蜀十三",
	gz_daqiush14: "大秋蜀十四",
	gz_daqiush15: "大秋蜀十五",
	gz_daqiush16: "大秋蜀十六",
	gz_daqiush17: "大秋蜀十七",
	gz_daqiush18: "大秋蜀十八",
	gz_daqiush19: "从蜀大秋魏十九",
	gz_miyanaga_teru: "宫永照",
	gz_amae_koromo: "天江衣",
};

export const sort = ["guozhan_ee_test", "测试包"];
