import { Character } from "../../../../noname/library/element/index.js";

import test from "./test.js";

/** @type {Record<string, Character>} */
export const pack = {
	gz_shibing1wei: new Character({
		sex: "male",
		group: "wei",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2wei: new Character({
		sex: "female",
		group: "wei",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1shu: new Character({
		sex: "male",
		group: "shu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2shu: new Character({
		sex: "female",
		group: "shu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1wu: new Character({
		sex: "male",
		group: "wu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2wu: new Character({
		sex: "female",
		group: "wu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1qun: new Character({
		sex: "male",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2qun: new Character({
		sex: "female",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1jin: new Character({
		sex: "male",
		group: "jin",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2jin: new Character({
		sex: "female",
		group: "jin",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1han: new Character({
		sex: "male",
		group: "han",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2han: new Character({
		sex: "female",
		group: "han",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1mahjong: new Character({
		sex: "male",
		group: "mahjong",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2mahjong: new Character({
		sex: "female",
		group: "mahjong",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing1ye: new Character({
		sex: "male",
		group: "ye",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	gz_shibing2ye: new Character({
		sex: "female",
		group: "ye",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
	}),
	// 双势力士兵 - C(4,2)=6
	gz_shibing1_qun_shu: new Character({ 
		sex: "male", 
		group: "qun", 
		hp: 0, 
		maxHp: 0, 
		hujia: 0, 
		skills: [], 
		isUnseen: true, 
		majorSecondGroup: "shu" 
	}),
	gz_shibing2_qun_shu: new Character({
		sex: "female",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "shu",
	}),
	gz_shibing1_qun_wei: new Character({
		sex: "male",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wei",
	}),
	gz_shibing2_qun_wei: new Character({
		sex: "female",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wei",
	}),
	gz_shibing1_qun_wu: new Character({
		sex: "male",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wu",
	}),
	gz_shibing2_qun_wu: new Character({
		sex: "female",
		group: "qun",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wu",
	}),
	gz_shibing1_shu_wei: new Character({
		sex: "male",
		group: "shu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wei",
	}),
	gz_shibing2_shu_wei: new Character({
		sex: "female",
		group: "shu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wei",
	}),
	gz_shibing1_shu_wu: new Character({
		sex: "male",
		group: "shu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wu",
	}),
	gz_shibing2_shu_wu: new Character({
		sex: "female",
		group: "shu",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wu",
	}),
	gz_shibing1_wei_wu: new Character({
		sex: "male",
		group: "wei",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wu",
	}),
	gz_shibing2_wei_wu: new Character({
		sex: "female",
		group: "wei",
		hp: 0,
		maxHp: 0,
		hujia: 0,
		skills: [],
		isUnseen: true,
		majorSecondGroup: "wu",
	}),

	...test,
};

export { default as intro } from "./intro.js";
export { default as sort } from "./sort.js";
