import { Character } from "../../../../noname/library/element/index.js";

export default {
	gz_daqiush0: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush1: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_daqiush_controlled_active", "gz_daqiush_enable_active", "gz_daqiush_disable_active", "gz_daqiush_controlled_passive", "gz_daqiush_enable_passive", "gz_daqiush_disable_passive"],
		majorSecondGroup: "wei",
	}),
	gz_daqiush2: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_daqiush_kill", "gz_daqiush_hide", "gz_daqiush_show", "gz_daqiush_infect", "gz_daqiush_changemain", "gz_daqiush_remove", "gz_daqiush_chengdi"],
		minorSecondGroup: "wei",
	}),
	gz_daqiush3: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_daqiush_kill", "gz_daqiush_hide", "gz_daqiush_show", "gz_daqiush_infect", "gz_daqiush_changemain", "gz_daqiush_remove", "gz_daqiush_chengdi"],
		minorSecondGroup: "shu",
	}),
	gz_daqiush4: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush5: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush6: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush7: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush8: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush9: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush10: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush11: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush12: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush13: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush14: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush15: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush16: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush17: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush18: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush19: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush20: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush21: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush22: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush23: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush24: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush25: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush26: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush27: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_miyanaga_teru: new Character({
		sex: "female",
		group: "mahjong",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["miyanaga_teru_yumo",
			"miyanaga_teru_yueleng", "miyanaga_teru_yueqing", 
			"miyanaga_teru_yueming", "miyanaga_teru_yuehui", 
			"miyanaga_teru_yueqingg", "miyanaga_teru_yuelian", 
			"miyanaga_teru_yueluo", "miyanaga_teru_yuehun"],
		hasSkinInGuozhan: true,
	}),
	gz_amae_koromo: new Character({
		sex: "female",
		group: "mahjong",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		isUnseen: true,
		skills: [],
		hasSkinInGuozhan: true,
	}),
};

export const intro = {
	gz_daqiush0: "测试武将描述",
	gz_daqiush1: "测试武将描述",
	gz_daqiush2: "测试武将描述",
	gz_daqiush3: "测试武将描述",
	gz_daqiush4: "测试武将描述",
	gz_daqiush5: "测试武将描述",
	gz_daqiush6: "测试武将描述",
	gz_daqiush7: "测试武将描述",
	gz_daqiush8: "测试武将描述",
	gz_daqiush9: "测试武将描述",
	gz_daqiush10: "测试武将描述",
	gz_daqiush11: "测试武将描述",
	gz_daqiush12: "测试武将描述",
	gz_daqiush13: "测试武将描述",
	gz_daqiush14: "测试武将描述",
	gz_daqiush15: "测试武将描述",
	gz_daqiush16: "测试武将描述",
	gz_daqiush17: "测试武将描述",
	gz_daqiush18: "测试武将描述",
	gz_daqiush19: "测试武将描述",
	gz_daqiush20: "测试武将描述",
	gz_daqiush21: "测试武将描述",
	gz_daqiush22: "测试武将描述",
	gz_daqiush23: "测试武将描述",
	gz_daqiush24: "测试武将描述",
	gz_daqiush25: "测试武将描述",
	gz_daqiush26: "测试武将描述",
	gz_daqiush27: "测试武将描述",
	gz_miyanaga_teru: "宫永咲的姐姐，被福与恒子称为“站在高中生顶点的人”，拥有目前天才麻将少女之中数一数二的麻将实力。是去年全国高中生麻将大赛以及春季大赛的两冠优胜者，以及今年全国高中生个人赛优胜候补，是“被牌爱着的孩子”的三人之一。全国个人赛第二名的荒川憩，称其不是人类。",
	gz_amae_koromo: "去年全国大赛的MVP选手。打法看起来像外行人一样，但在全国大赛中一回战击飞两家、二回战击飞三家，是知名的高火力选手。曾和职业雀士藤田靖子一起参加过某个友谊赛，因得点最高而拿下了冠军。",
};

export const sort = "guozhan_ee_test";
