import { Character } from "../../../../noname/library/element/index.js";

export default {
	gz_daqiush0: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush1: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_daqiush_controlled", "gz_daqiush_enable", "gz_daqiush_disable"],
		majorSecondGroup: "wei",
	}),
	gz_daqiush2: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_daqiush_kill", "gz_daqiush_hide", "gz_daqiush_show", "gz_daqiush_infect"],
		minorSecondGroup: "wei",
	}),
	gz_daqiush3: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush4: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush5: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush6: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush7: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush8: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush9: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush10: new Character({
		sex: "male",
		group: "han",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush11: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush12: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush13: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush14: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush15: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush16: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush17: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush18: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: [],
	}),
	gz_daqiush19: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_daqiush_kill", "gz_daqiush_hide", "gz_daqiush_show", "gz_daqiush_infect"],
		minorSecondGroup: "shu",
	}),
};

export const intro = {
	gz_daqiush0: "测试武将描述",
	gz_daqiush1: "测试武将描述",
	gz_daqiush2: "测试武将描述",
	gz_daqiush3: "测试武将描述",
	gz_daqiush4: "测试武将描述",
	gz_daqiush5: "测试武将描述",
	gz_daqiush6: "测试武将描述",
	gz_daqiush7: "测试武将描述",
	gz_daqiush8: "测试武将描述",
	gz_daqiush9: "测试武将描述",
	gz_daqiush10: "测试武将描述",
	gz_daqiush11: "测试武将描述",
	gz_daqiush12: "测试武将描述",
	gz_daqiush13: "测试武将描述",
	gz_daqiush14: "测试武将描述",
	gz_daqiush15: "测试武将描述",
	gz_daqiush16: "测试武将描述",
	gz_daqiush17: "测试武将描述",
	gz_daqiush18: "测试武将描述",
	gz_daqiush19: "测试武将描述",
};

export const sort = "guozhan_ee_test";
