export default {
	gz_daqiush_kill: "秒杀",
	gz_daqiush_kill_info: "出牌阶段，你可以对一名角色造成100点伤害。",
	gz_daqiush_hide: "暗将",
	gz_daqiush_hide_info: "出牌阶段，你可以令一名角色暗置主将或副将。",
	gz_daqiush_show: "明将",
	gz_daqiush_show_info: "出牌阶段，你可以令一名角色明置主将或副将。",
	gz_daqiush_infect: "传染",
	gz_daqiush_infect_info: "出牌阶段，你可以将自己的副将传染给一名角色。",
	gz_daqiush_changemain: "换主",
	gz_daqiush_changemain_info: "出牌阶段，你可以令一名角色变更主将。",
	gz_daqiush_remove: "移除",
	gz_daqiush_remove_info: "出牌阶段，你可以令一名角色移除主将或副将。",
	gz_daqiush_chengdi: "撑地",
	gz_daqiush_chengdi_info: "锁定技。游戏开始时，你将下家的副将替换为“魏大秋蜀一”，下下家的副将替换为“大秋蜀十一”，然后上家获得一张玉玺和火烧连营并使用。",

	gz_daqiush_controlled_active: "受控（主）",
	gz_daqiush_controlled_active_info: "失能。出牌阶段，你可以摸两张牌。",
	gz_daqiush_enable_active: "使能（主）",
	gz_daqiush_enable_active_info: "出牌阶段，你可以使能技能“受控（主）”。",
	gz_daqiush_disable_active: "失能（主）",
	gz_daqiush_disable_active_info: "出牌阶段，你可以失能技能“受控（主）”。",
	gz_daqiush_controlled_passive: "受控（被）",
	gz_daqiush_controlled_passive_info: "使能。当你受到伤害后，你可以回复等量体力。",
	gz_daqiush_enable_passive: "使能（被）",
	gz_daqiush_enable_passive_info: "出牌阶段，你可以使能技能“受控（被）”。",
	gz_daqiush_disable_passive: "失能（被）",
	gz_daqiush_disable_passive_info: "出牌阶段，你可以失能技能“受控（被）”。",

	miyanaga_teru_yumo: "玉魔",
	miyanaga_teru_yumo_info: "使能，明置技，将你的副将替换为天江衣。每个回合开始时，你失能此技能，秘密指定一个花色X，并断言本回合第一张由其他角色使用且有花色的牌的花色为此花色。</br>成功：使能【月冷】。本回合结束时，从弃牌堆中获得此牌。</br>失败：使能【玉魔】。",
	miyanaga_teru_yueleng: "月冷",
	miyanaga_teru_yueleng_info: "1",
	miyanaga_teru_yueqing: "月清",
	miyanaga_teru_yueqing_info: "2",
	miyanaga_teru_yueming: "月明",
	miyanaga_teru_yueming_info: "3",
	miyanaga_teru_yuehui: "月晦",
	miyanaga_teru_yuehui_info: "4",
	miyanaga_teru_yueqingg: "月情",
	miyanaga_teru_yueqingg_info: "5",
	miyanaga_teru_yuelian: "月恋",
	miyanaga_teru_yuelian_info: "6",
	miyanaga_teru_yueluo: "月落",
	miyanaga_teru_yueluo_info: "7",
	miyanaga_teru_yuehun: "月魂",
	miyanaga_teru_yuehun_info: "8",
};
