export default {
	vibe_mashu: "马术（老母鸡）",
	vibe_mashu_info: "明置技，你计算到其他角色的距离时，始终-1。",
	bazhen_bagua_ee: "八阵",

	vibe_zhugeliang_huoji: "火计",
	vibe_zhugeliang_huoji_info: "出牌阶段限一次，你可以将一张红色手牌转化为【火攻】。你使用【火攻】时可以选择修改一项本次【火攻】中的描述：1.弃置->展示；2.花色->颜色；3.其->其与其同一队列的其他角色。",
	vibe_zhugeliang_kanpo: "看破",
	vibe_zhugeliang_kanpo_info: "你可以将一张黑色手牌转化为【无懈可击】。",
	vibe_zhugeliang_bazhen: "八阵",
	vibe_zhugeliang_bazhen_info: "<b>明置技</b>，若不为你的回合，获得前回合角色的一张牌。若你没有防具，视为装备【八卦阵】。<br>",

	vibe_zhaoyun_longdan: "龙胆",
	vibe_zhaoyun_longdan_info: "你可以将手牌区中的一张【杀】/【闪】转化为【杀/闪】。",
	vibe_zhaoyun_yajiao: "涯角",
	vibe_zhaoyun_yajiao_info: "每回合各限一次：<br>1.当你使用【杀/闪】时，你可以摸一张牌；<br>2.当你打出【杀/闪】时，你可以获得当前回合角色的一张手牌。",

	vibe_jiangqin_shangyi: "尚义",
	vibe_jiangqin_shangyi_info: "出牌阶段限一次，你可以令一名其他角色观看你的手牌。若如此做，你选择一项：<br>1.观看其手牌并可以弃置/重铸其一张黑/红色牌；<br>2.观看其暗置的武将牌且其本回合不能明置之。",
	vibe_jiangqin_jianyi: "俭衣",
	vibe_jiangqin_jianyi_info: "当你需要使用一张普【杀】/普【无懈可击】时，你可以使用一张装备手牌，然后视为使用所需使用的牌。若替换原装备牌，你可以令此牌不能被抵消或不计入次数。",

	vibe_bianfuren_yide: "仪德",
	vibe_bianfuren_yide_info: "相同势力的角色受到伤害时，若伤害来源是与另一名相同势力的角色，你可防止之。",
	vibe_bianfuren_cijie: "慈诫",
	vibe_bianfuren_cijie_info: "相同势力的角色于其出牌阶段使用【桃】选择目标后，可以指定另任意名已受伤角色为额外目标，若如此做，你变更此武将。",
	vibe_bianfuren_yuejian: "约俭",
	vibe_bianfuren_yuejian_info: "每回合限一次，相同势力角色弃置自己的牌后，你可以令其选择其中一张，然后其获得之。",

	vibe_zhuhuan_jutian: "拒天",
	vibe_zhuhuan_jutian_info: "每回合各限一次，当你对一名其他角色造成伤害后，你可以选择一项：<br>1.令一名与其势力相同的角色将手牌弃至受伤害角色的体力值；<br>2.令一名与你势力相同的角色将手牌摸至受伤害角色的体力上限。",

	vibe_xurong_shajue: "杀绝",
	vibe_xurong_shajue_info: "出牌阶段每名角色限一次，你可以弃置一名手牌数为1的角色的一张手牌，然后视为对除其以外的一名其他角色使用一张【决斗】，以此法使用的【决斗】对没有手牌的角色造成的伤害+1。",

	vibe_mengda_hubian: "狐变",
	vibe_mengda_hubian_info: "当你受到伤害后，你可变更主将，然后若你的势力因此变化，你摸X张牌（X为此前相同势力角色数）。",
	vibe_mengda_chenzhong: "陈忠",
	vibe_mengda_chenzhong_info: "<b>蜀势力技</b>，锁定技，若有其他友方角色，你使用【杀】的目标改为由所有其他友方角色投票指定（须合法）。",
	vibe_mengda_liangfan: "量反",
	vibe_mengda_liangfan_info: "<b>魏势力技</b>，锁定技，出牌阶段开始时，你令所有其他友方角色投票选出友方角色，所有得票最多的角色同时与你选择的另一名角色拼点，赢的角色视为对没赢的角色使用一张【杀】。",
	vibe_mengda_qiuan: "求安",
	vibe_mengda_qiuan_info: "<b>野心家势力技</b>，限定技：你变更主将前，可永久暴露野心，若如此做：本局游戏中，此武将牌可以搭配任何势力的主将；你变更主将后可以交换主副将至下次变更前。",

	vibe_caocao_huibian: "挥鞭",
	vibe_caocao_huibian_info: "当你受到1点伤害后，你可以选择一项：</br>1.令一名非当前回合角色获得造成此伤害的牌，然后其交给你一张手牌；</br>2.令一名势力与你明确相同的角色招募。",
	vibe_simayi_guicai: "鬼才",
	vibe_simayi_guicai_info: "当一名角色的判定牌生效前，你可以打出一张牌代替之，每回合每种花色限一次。",
	vibe_simayi_langgu: "狼顾",
	vibe_simayi_langgu_info: "摸牌阶段，你可以少摸一张牌并获得当前回合角色的一张手牌。",
	vibe_simayi_lianpo: "连破",
	vibe_simayi_lianpo_info: "每轮限一次，每回合结束时，若你本回合杀死过其他角色，你可以获得一个额外的回合。",

	vibe_liubei_rende: "仁德",
	vibe_liubei_rende_info: "出牌阶段限一次，你可以将X张手牌分别交给任意名其他角色，然后若X不小于2且你没有<b>【仁望】</b>，你获得<b>【仁望】</b>；若X大于相同势力角色数，你可令一名势力与你明确相同的角色招募。",
	vibe_liubei_renwang: "仁望",
	vibe_liubei_renwang_info: "当你于回合内需要使用/打出一张基本牌时，你可以视为使用/打出之，然后你失去<b>【仁望】</b>。",

	vibe_guanyu_wusheng: "武圣",
	vibe_guanyu_wusheng_info: "你可以将一张红色手牌转化为【杀】。",
	vibe_guanyu_weilin: "威临",
	vibe_guanyu_weilin_info: "<b>主将技</b>。奥秘技，你的体力上限-1（取一个单独阴阳鱼）。战吼，当前结算结束后，可以视为使用一张【水淹七军】。<b>明置技</b>，你使用的♦【杀】无距离限制。<b>锁定技</b>，你使用♥【杀】指定目标后，令其防具技能无效直到此【杀】结算结束。",
	vibe_guanyu_weilin_zhanhao: "战吼",
	vibe_guanyu_weilin_zhanhao_info: "当前结算结束后，可以视为使用一张【水淹七军】。",
};
