import { lib, game, ui, get, ai, _status } from "../../../../noname.js";

export default {
	test: "测试包",
	_hezong: "合纵",
	hezong_tag: "合",
	guo_tag: "国",
	_guozhan_marks: "标记",
	_guozhan_marks_backup: "标记",
	xianqu_mark: "先驱",
	zhulianbihe_mark: "珠联璧合",
	yinyang_mark: "阴阳鱼",
	_zhulianbihe_mark_tao: "珠联",
	_yinyang_mark_add: "阴阳鱼",
	yinyang_add: "阴阳鱼",
	// 兵种翻译
	gz_shibing1wei: "魏兵",
	gz_shibing2wei: "魏卒",
	gz_shibing1shu: "蜀兵",
	gz_shibing2shu: "蜀卒",
	gz_shibing1wu: "吴兵",
	gz_shibing2wu: "吴卒",
	gz_shibing1qun: "群兵",
	gz_shibing2qun: "群卒",
	gz_shibing1jin: "晋兵",
	gz_shibing2jin: "晋卒",
	gz_shibing1han: "汉兵",
	gz_shibing2han: "汉卒",
	gz_shibing1mahjong: "雀兵",
	gz_shibing2mahjong: "雀卒",
	gz_shibing1ye: "野兵",
	gz_shibing2ye: "野卒",
	gz_shibing1_qun_shu: "群蜀兵",
	gz_shibing2_qun_shu: "群蜀卒",
	gz_shibing1_qun_wei: "群魏兵",
	gz_shibing2_qun_wei: "群魏卒",
	gz_shibing1_qun_wu: "群吴兵",
	gz_shibing2_qun_wu: "群吴卒",
	gz_shibing1_shu_wei: "蜀魏兵",
	gz_shibing2_shu_wei: "蜀魏卒",
	gz_shibing1_shu_wu: "蜀吴兵",
	gz_shibing2_shu_wu: "蜀吴卒",
	gz_shibing1_wei_wu: "魏吴兵",
	gz_shibing2_wei_wu: "魏吴卒",
};
